//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureIoTHubConnectedService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureIoTHubConnectedService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string CreateHubLocation {
            get {
                return ResourceManager.GetString("CreateHubLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub Name.
        /// </summary>
        public static string CreateHubName {
            get {
                return ResourceManager.GetString("CreateHubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Group.
        /// </summary>
        public static string CreateHubResourceGroup {
            get {
                return ResourceManager.GetString("CreateHubResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string CreateHubSubscription {
            get {
                return ResourceManager.GetString("CreateHubSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New IoT Hub.
        /// </summary>
        public static string CreateServiceInstanceText {
            get {
                return ResourceManager.GetString("CreateServiceInstanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create device &apos;{0}&apos;. IoT Hub returned an error..
        /// </summary>
        public static string DeviceCreationFailure {
            get {
                return ResourceManager.GetString("DeviceCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate device twin sample code.
        /// </summary>
        public static string DeviceOptionDeviceTwin {
            get {
                return ResourceManager.GetString("DeviceOptionDeviceTwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins.
        /// </summary>
        public static string DeviceOptionDeviceTwinLink {
            get {
                return ResourceManager.GetString("DeviceOptionDeviceTwinLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate direct method sample code.
        /// </summary>
        public static string DeviceOptionDirectMethod {
            get {
                return ResourceManager.GetString("DeviceOptionDirectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods.
        /// </summary>
        public static string DeviceOptionDirectMethodLink {
            get {
                return ResourceManager.GetString("DeviceOptionDirectMethodLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate sample code that receives messages.
        /// </summary>
        public static string DeviceOptionReceivingMsgs {
            get {
                return ResourceManager.GetString("DeviceOptionReceivingMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate sample code to send messages.
        /// </summary>
        public static string DeviceOptionSendingMsgs {
            get {
                return ResourceManager.GetString("DeviceOptionSendingMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily and securely connect your devices to Azure IoT Hub. You can send device-to-cloud and device-to-cloud messages, plus utilize device management capabilities to reliably update devices.
        /// </summary>
        public static string ExtensionDescription {
            get {
                return ResourceManager.GetString("ExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &apos;{0}&apos; already exists. Do you want to replace it?.
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing IoT Hub or create a new one by clicking the link below..
        /// </summary>
        public static string GridHeaderText {
            get {
                return ResourceManager.GetString("GridHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub Name.
        /// </summary>
        public static string HubListHeaderName {
            get {
                return ResourceManager.GetString("HubListHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string HubListHeaderRegion {
            get {
                return ResourceManager.GetString("HubListHeaderRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string HubListHeaderSubscription {
            get {
                return ResourceManager.GetString("HubListHeaderSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate between your devices and Azure IoT Hub..
        /// </summary>
        public static string IoTHubProvdierDescription {
            get {
                return ResourceManager.GetString("IoTHubProvdierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string LabelAdvancedOptions {
            get {
                return ResourceManager.GetString("LabelAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        public static string LabelDeviceId {
            get {
                return ResourceManager.GetString("LabelDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Devices....
        /// </summary>
        public static string LoadingDevices {
            get {
                return ResourceManager.GetString("LoadingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet package &apos;{0}&apos; version {1}..
        /// </summary>
        public static string LogMessage_AddingNuGetPackage {
            get {
                return ResourceManager.GetString("LogMessage_AddingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code being added depends on NuGet package ‘{0}’ version {1}.  A newer version ({2}) is already installed.  This may cause compatibility issues..
        /// </summary>
        public static string LogMessage_NewerMajorVersionNuGetPackageExists {
            get {
                return ResourceManager.GetString("LogMessage_NewerMajorVersionNuGetPackageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading NuGet package &apos;{0}&apos; from version {1} to {2}.  A major version upgrade may introduce compatibility issues with existing code..
        /// </summary>
        public static string LogMessage_OlderMajorVersionNuGetPackageExists {
            get {
                return ResourceManager.GetString("LogMessage_OlderMajorVersionNuGetPackageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling NuGet package &apos;{0}&apos; version {1}..
        /// </summary>
        public static string LogMessage_RemovingNuGetPackage {
            get {
                return ResourceManager.GetString("LogMessage_RemovingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading NuGet package &apos;{0}&apos; from version {1} to {2}..
        /// </summary>
        public static string LogMessage_UpgradingNuGetPackage {
            get {
                return ResourceManager.GetString("LogMessage_UpgradingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more info....
        /// </summary>
        public static string MoreInfoLink {
            get {
                return ResourceManager.GetString("MoreInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view your IoT Hubs, add a user account or reenter your credentials..
        /// </summary>
        public static string NeedToAuthenticateText {
            get {
                return ResourceManager.GetString("NeedToAuthenticateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IoT Hub instances were found.  Choose another user or create a new IoT Hub instance from Azure Portal..
        /// </summary>
        public static string NoServiceInstancesText {
            get {
                return ResourceManager.GetString("NoServiceInstancesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Device.
        /// </summary>
        public static string ProvisionButton {
            get {
                return ResourceManager.GetString("ProvisionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID (stored on the device).
        /// </summary>
        public static string ProvisionDeviceId {
            get {
                return ResourceManager.GetString("ProvisionDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device shared key (stored on the device).
        /// </summary>
        public static string ProvisionDeviceKey {
            get {
                return ResourceManager.GetString("ProvisionDeviceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub URI (stored in application code).
        /// </summary>
        public static string ProvisionHubUri {
            get {
                return ResourceManager.GetString("ProvisionHubUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Group.
        /// </summary>
        public static string ResourceGroup {
            get {
                return ResourceManager.GetString("ResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub Name.
        /// </summary>
        public static string ServiceInstanceNameLabelText {
            get {
                return ResourceManager.GetString("ServiceInstanceNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string SummaryDevice {
            get {
                return ResourceManager.GetString("SummaryDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Primary Connection String.
        /// </summary>
        public static string SummaryDevicePrimaryConnectionString {
            get {
                return ResourceManager.GetString("SummaryDevicePrimaryConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Secondary Connection String.
        /// </summary>
        public static string SummaryDeviceSecondaryConnectionString {
            get {
                return ResourceManager.GetString("SummaryDeviceSecondaryConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub.
        /// </summary>
        public static string SummaryIoTHub {
            get {
                return ResourceManager.GetString("SummaryIoTHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub Connection String.
        /// </summary>
        public static string SummaryIoTHubConnectionString {
            get {
                return ResourceManager.GetString("SummaryIoTHubConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string SummarySubscription {
            get {
                return ResourceManager.GetString("SummarySubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TabHeaderCreate {
            get {
                return ResourceManager.GetString("TabHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device.
        /// </summary>
        public static string TabHeaderNewDevice {
            get {
                return ResourceManager.GetString("TabHeaderNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string TabHeaderSelect {
            get {
                return ResourceManager.GetString("TabHeaderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string Tier {
            get {
                return ResourceManager.GetString("Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcode shared access key in application&apos;s code..
        /// </summary>
        public static string WizardOptionHardcode {
            get {
                return ResourceManager.GetString("WizardOptionHardcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device-specific shared access key is retrieved from your Azure subscription and embedded in the source code..
        /// </summary>
        public static string WizardOptionHardcodeDescription {
            get {
                return ResourceManager.GetString("WizardOptionHardcodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision device..
        /// </summary>
        public static string WizardOptionProvision {
            get {
                return ResourceManager.GetString("WizardOptionProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device-specific shared access key is retrieved from your Azure subscription and stored on the device..
        /// </summary>
        public static string WizardOptionProvisionDescription {
            get {
                return ResourceManager.GetString("WizardOptionProvisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Experimental) Use Azure device credentials stored in the TPM..
        /// </summary>
        public static string WizardOptionTpm {
            get {
                return ResourceManager.GetString("WizardOptionTpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires device provisioning using WebB or IoT Dashboard..
        /// </summary>
        public static string WizardOptionTpmDescription {
            get {
                return ResourceManager.GetString("WizardOptionTpmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing device or create a new one.
        /// </summary>
        public static string WizardPageDeviceSelectionDescription {
            get {
                return ResourceManager.GetString("WizardPageDeviceSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string WizardPageDeviceSelectionLegend {
            get {
                return ResourceManager.GetString("WizardPageDeviceSelectionLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing IoT hub or create a new one.
        /// </summary>
        public static string WizardPageHubSelectionDescription {
            get {
                return ResourceManager.GetString("WizardPageHubSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Hub.
        /// </summary>
        public static string WizardPageHubSelectionLegend {
            get {
                return ResourceManager.GetString("WizardPageHubSelectionLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store device id and shared key on your device.
        /// </summary>
        public static string WizardPageInjectConnectionStringDescription {
            get {
                return ResourceManager.GetString("WizardPageInjectConnectionStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Device.
        /// </summary>
        public static string WizardPageInjectConnectionStringLegend {
            get {
                return ResourceManager.GetString("WizardPageInjectConnectionStringLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Azure.
        /// </summary>
        public static string WizardPageLoginDescription {
            get {
                return ResourceManager.GetString("WizardPageLoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string WizardPageLoginLegend {
            get {
                return ResourceManager.GetString("WizardPageLoginLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string WizardPageSummaryDescription {
            get {
                return ResourceManager.GetString("WizardPageSummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string WizardPageSummaryLegend {
            get {
                return ResourceManager.GetString("WizardPageSummaryLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure IoT Hub.
        /// </summary>
        public static string WizardPageTitle {
            get {
                return ResourceManager.GetString("WizardPageTitle", resourceCulture);
            }
        }
    }
}
